name: flux_validator_dart
version: 1.0.1
authors:
- Lucas Yarid <lucas.boccuzi@doc88.com.br>
- Giovanni Spolidorio <giovanni.spolidorio@doc88.com.br>
description: >
  A package to validate strings and input data for dart.
homepage: https://github.com/doc88git/flux_validator_dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter